/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** disbursement to token */
export interface ABAToken {
  disbursementMethod: string;
  /** description for the transaction */
  description?: string;
  /** The text (GUID) that identifies the token */
  toToken: string;
  /** This is the amount of funds to be paid */
  amount: number;
  /** Reference will appear on payees statement. Refer to the disbursement object, May be overwritten for some account configurations,contact us for more details. */
  lodgementReference?: string;
}

export const aBATokenSchema: Schema<ABAToken> = object({
  disbursementMethod: ['disbursementMethod', string()],
  description: ['description', optional(string())],
  toToken: ['toToken', string()],
  amount: ['amount', number()],
  lodgementReference: ['lodgementReference', optional(string())],
});
