/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AccountStatusEnum
 */
export enum AccountStatusEnum {
  Enabled = 'enabled',
  Disabled = 'disabled',
}

/**
 * Schema for AccountStatusEnum
 */
export const accountStatusEnumSchema: Schema<AccountStatusEnum> = stringEnum(AccountStatusEnum);
