/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema';

export interface BpayReceipts {
  /** The date for which Monoova received the BPAY Receivable transactions. "yyyy-MM-dd" format. */
  date?: string;
  /** This is the BPAY biller code that was requested. billerCodemust be numeric */
  billerCode?: string;
  /** Customer Reference Number as shown on the Bill. Must be a valid BPAY Customer Reference Number on token creation. */
  customerReferenceNumber?: bigint;
  /** This is a unique reference generated by the calling service. This is a nonce. Its use is to determine if a request has already been received by the Engine. We strongly recommend sending a uniqueReference in your execution call to avoid duplicate transactions. */
  uniqueReference?: string;
}

export const bpayReceiptsSchema: Schema<BpayReceipts> = object({
  date: ['date', optional(string())],
  billerCode: ['billerCode', optional(string())],
  customerReferenceNumber: ['CustomerReferenceNumber', optional(bigint())],
  uniqueReference: ['uniqueReference', optional(string())],
});
