/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { ToBPayDetails, toBPayDetailsSchema } from './toBPayDetails';

/** disbursement to BPAY */
export interface BPAY {
  disbursementMethod: string;
  /** description for the transaction */
  description?: string;
  toBPayDetails: ToBPayDetails;
  /** This is the amount of funds to be paid */
  amount: number;
}

export const bPAYSchema: Schema<BPAY> = object({
  disbursementMethod: ['disbursementMethod', string()],
  description: ['description', optional(string())],
  toBPayDetails: ['toBPayDetails', lazy(() => toBPayDetailsSchema)],
  amount: ['amount', number()],
});
