/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import { Key2Enum, key2EnumSchema } from './key2Enum';

export interface CreditTplusXDays {
  key?: Key2Enum;
  value?: number;
}

export const creditTplusXDaysSchema: Schema<CreditTplusXDays> = object({
  key: ['key', optional(key2EnumSchema)],
  value: ['value', optional(number())],
});
