/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import { Key1Enum, key1EnumSchema } from './key1Enum';

export interface DebitTplusXDays {
  key?: Key1Enum;
  value?: number;
}

export const debitTplusXDaysSchema: Schema<DebitTplusXDays> = object({
  key: ['key', optional(key1EnumSchema)],
  value: ['value', optional(number())],
});
