/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import {
  ToDirectCreditDetails,
  toDirectCreditDetailsSchema,
} from './toDirectCreditDetails';

/** disbursement to directCredit */
export interface DirectCredit {
  disbursementMethod: string;
  /** description for the transaction */
  description?: string;
  toDirectCreditDetails: ToDirectCreditDetails;
  /** This is the amount of funds to be paid */
  amount: number;
  /** Reference will appear on payees statement. Refer to the disbursement object, May be overwritten for some account configurations, contact us for more details. */
  lodgementReference?: string;
}

export const directCreditSchema: Schema<DirectCredit> = object({
  disbursementMethod: ['disbursementMethod', string()],
  description: ['description', optional(string())],
  toDirectCreditDetails: [
    'toDirectCreditDetails',
    lazy(() => toDirectCreditDetailsSchema),
  ],
  amount: ['amount', number()],
  lodgementReference: ['lodgementReference', optional(string())],
});
