/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface DirectDebit {
  /** BSB (Bank-State-Branch) number. The format is a string in the following format:&nbsp;‘999-999’. */
  bsbNumber?: string;
  /** This is the bank account number. Range of '100' to '999999999' */
  accountNumber?: number;
  /** This is the name of the account. Minimum length is 2, Max length is 32. */
  accountName?: string;
}

export const directDebitSchema: Schema<DirectDebit> = object({
  bsbNumber: ['bsbNumber', optional(string())],
  accountNumber: ['accountNumber', optional(number())],
  accountName: ['accountName', optional(string())],
});
