/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DisbursementMethodEnum
 */
export enum DisbursementMethodEnum {
  DirectCredit = 'directCredit',
}

/**
 * Schema for DisbursementMethodEnum
 */
export const disbursementMethodEnumSchema: Schema<DisbursementMethodEnum> = stringEnum(DisbursementMethodEnum);
