/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DisbursementMethod1Enum
 */
export enum DisbursementMethod1Enum {
  MAccount = 'mAccount',
}

/**
 * Schema for DisbursementMethod1Enum
 */
export const disbursementMethod1EnumSchema: Schema<DisbursementMethod1Enum> = stringEnum(DisbursementMethod1Enum);
