/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import {
  DisbursementMethod1Enum,
  disbursementMethod1EnumSchema,
} from './disbursementMethod1Enum';
import { ToBPayDetails, toBPayDetailsSchema } from './toBPayDetails';
import {
  ToDirectCreditDetails,
  toDirectCreditDetailsSchema,
} from './toDirectCreditDetails';
import {
  ToNppCreditBankAccountDetails,
  toNppCreditBankAccountDetailsSchema,
} from './toNppCreditBankAccountDetails';
import {
  ToNppCreditPayIdDetails,
  toNppCreditPayIdDetailsSchema,
} from './toNppCreditPayIdDetails';

export interface Disbursement1 {
  disbursementMethod?: DisbursementMethod1Enum;
  /** description for the transaction */
  description?: string;
  /** 16-Digit account number that uniquely identifies the mAccount */
  toMAccount?: string;
  /** This is the amount of funds to be paid */
  amount?: number;
  /** 16-Digit account number that uniquely identifies the mWallet */
  toMWallet?: string;
  toDirectCreditDetails?: ToDirectCreditDetails;
  /** Reference will appear on payees statement. Refer to the disbursement object, May be overwritten for some account configurations, contact us for more details. */
  lodgementReference?: string;
  /** The text (GUID) that identifies the token */
  toToken?: string;
  toBPayDetails?: ToBPayDetails;
  toNppCreditBankAccountDetails?: ToNppCreditBankAccountDetails;
  toNppCreditPayIdDetails?: ToNppCreditPayIdDetails;
}

export const disbursement1Schema: Schema<Disbursement1> = object({
  disbursementMethod: [
    'disbursementMethod',
    optional(disbursementMethod1EnumSchema),
  ],
  description: ['description', optional(string())],
  toMAccount: ['toMAccount', optional(string())],
  amount: ['amount', optional(number())],
  toMWallet: ['toMWallet', optional(string())],
  toDirectCreditDetails: [
    'toDirectCreditDetails',
    optional(lazy(() => toDirectCreditDetailsSchema)),
  ],
  lodgementReference: ['lodgementReference', optional(string())],
  toToken: ['toToken', optional(string())],
  toBPayDetails: ['toBPayDetails', optional(lazy(() => toBPayDetailsSchema))],
  toNppCreditBankAccountDetails: [
    'toNppCreditBankAccountDetails',
    optional(lazy(() => toNppCreditBankAccountDetailsSchema)),
  ],
  toNppCreditPayIdDetails: [
    'toNppCreditPayIdDetails',
    optional(lazy(() => toNppCreditPayIdDetailsSchema)),
  ],
});
