/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { discriminatedObject, Schema } from '../schema';
import { financialTransactionSchema } from './financialTransaction';
import { paymentSourceDirectDebitSchema } from './paymentSourceDirectDebit';
import { paymentSourceMAccountSchema } from './paymentSourceMAccount';
import { paymentSourceMWalletSchema } from './paymentSourceMWallet';
import { paymentSourceTokenSchema } from './paymentSourceToken';

export const discriminatedFinancialTransactionSchema: Schema<any> = discriminatedObject(
  'paymentSource',
  'paymentSource',
  {
    'financial.transaction': financialTransactionSchema,
    'mAccount': paymentSourceMAccountSchema,
    'token': paymentSourceTokenSchema,
    'mWallet': paymentSourceMWalletSchema,
    'directDebit': paymentSourceDirectDebitSchema,
 },
  'financial.transaction'
);

