/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface DTOBPayHistoryItemV1 {
  /** BPAY Biller code */
  billerCode?: string;
  /** BBPAY Customer Reference Number. If this field is empty this denotes that the customerReferenceNumber is variable for each bill and should not be reused */
  customerReferenceNumber?: string;
  /** Long form of the BPAY Biller Name */
  billerName?: string;
  /** The number of usages of these detailsthat the mWallet has succeeded in paying previously */
  count?: number;
}

export const dTOBPayHistoryItemV1Schema: Schema<DTOBPayHistoryItemV1> = object({
  billerCode: ['billerCode', optional(string())],
  customerReferenceNumber: ['customerReferenceNumber', optional(string())],
  billerName: ['billerName', optional(string())],
  count: ['count', optional(number())],
});
