/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { DTOBPAYBillerV1, dTOBPAYBillerV1Schema } from './dTOBPAYBillerV1';

export interface DTOBPAYBillersResponseV1 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  durationMs?: bigint;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors */
  status?: string;
  /** This is a plain English description of the status. */
  statusDescription?: string;
  /** Text string to search for */
  search?: string;
  /** The total number of BPAYBiller’s that match the search criteria */
  totalCount?: number;
  /** The search string */
  skip?: number;
  /** The number of records that were requested */
  take?: number;
  billers?: DTOBPAYBillerV1[];
}

export const dTOBPAYBillersResponseV1Schema: Schema<DTOBPAYBillersResponseV1> = object(
  {
    durationMs: ['durationMs', optional(bigint())],
    status: ['status', optional(string())],
    statusDescription: ['statusDescription', optional(string())],
    search: ['search', optional(string())],
    totalCount: ['totalCount', optional(number())],
    skip: ['skip', optional(number())],
    take: ['take', optional(number())],
    billers: ['billers', optional(array(lazy(() => dTOBPAYBillerV1Schema)))],
  }
);
