/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface DTOBPAYValidationV1 {
  /** This is the BPAY biller code that was used to validate. billerCode must be numeric */
  billerCode?: string;
  /** This is the BPAY customer reference number that was used to validate. customerReferenceNumber must be numeric */
  customerReferenceNumber?: string;
  /** This is the amount that was used to validate. The maximum value of the field is $9999999999.99 however BPAY Billers will generally restrict the maximum value accepted for bill payment */
  amount?: string;
  /** This is the BPAY biller long name associated with the billerCode */
  billerName?: string;
  /** Indicates whether BPAY Customer Reference Numbers(CRN) for this biller change for each individual customer’s bill or do they remain the same.Non variable CRNs can be stored and used later, however they must always be validated as part of paying a bill via the gateway.Variable CRNs should not be stored as they are incorrect for subsequent bills. */
  isVariableCrn?: boolean;
  /** This is the minimum amount that the BPAY biller associated with the billerCode accepts for bill payment */
  minimumPaymentAmount?: number;
  /** This is the maximum amount that the BPAY biller associated with the billerCode accepts for bill payment */
  maximumPaymentAmount?: number;
}

export const dTOBPAYValidationV1Schema: Schema<DTOBPAYValidationV1> = object({
  billerCode: ['billerCode', optional(string())],
  customerReferenceNumber: ['customerReferenceNumber', optional(string())],
  amount: ['amount', optional(string())],
  billerName: ['billerName', optional(string())],
  isVariableCrn: ['isVariableCrn', optional(boolean())],
  minimumPaymentAmount: ['minimumPaymentAmount', optional(number())],
  maximumPaymentAmount: ['maximumPaymentAmount', optional(number())],
});
