/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface DTOBPAYReceiptV1 {
  /** This is the BPAY biller code that was requested. billerCodemust be numeric */
  billerCode?: string;
  /** This is the BPAY biller long name associated with the billerCode */
  billerName?: string;
  /** BBPAY receipt Number. */
  receiptNumber?: string;
  /** BBPAY Customer Reference Number. If this field is empty this denotes that the customerReferenceNumber is variable for each bill and should not be reused */
  referenceNumber?: string;
  /** Status of BPAY receipts */
  status?: string;
  /** The date time that the transaction was executed on the Platform Servers. Format is ISO8601 - 2015 -09 - 01T19: 19:58 */
  transactionDateTime?: string;
  /** The date time that the transaction was void on the Platform Servers */
  voidDateTime?: string;
}

export const dTOBPAYReceiptV1Schema: Schema<DTOBPAYReceiptV1> = object({
  billerCode: ['billerCode', optional(string())],
  billerName: ['billerName', optional(string())],
  receiptNumber: ['receiptNumber', optional(string())],
  referenceNumber: ['referenceNumber', optional(string())],
  status: ['status', optional(string())],
  transactionDateTime: ['transactionDateTime', optional(string())],
  voidDateTime: ['voidDateTime', optional(string())],
});
