/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface DTOBPAYBillerV1 {
  /** This is the BPAY biller code that was requested. billerCodemust be numeric */
  billerCode?: string;
  /** A long description of the billername */
  billerLongName?: string;
  /** A short decription of the billername */
  billerShortName?: string;
  /** Must be set to “1”. Field reserved for future expansion */
  acceptedPaymentMethods?: string;
  /** Date this biller was activated for BPAY. ISO 8601 date format with time set to 00:00:00. Note that Timezone is suppressed.The example Timezone is Sydney local time */
  activationDate?: string;
  /** Date this biller was deactivated for BPAY. ISO 8601 date format with time set to  00:00:00 or an empty string if not deactivated.Note that Timezone is suppressed.The example Timezone is Sydney local time */
  deactivationDate?: string;
  /** This is the minimum amount that the BPAY biller associated with the billerCodeaccepts for bill payment */
  minPaymentAmount?: number;
  /** This is the maximum amount that the BPAY biller associated with the billerCodeaccepts for bill payment */
  maxPaymentAmount?: number;
  /** For internal use only. Set to an empty string */
  crnValidationRuleName?: string;
  /** For internal use only. Set to an empty string */
  checkDigitRuleName?: string;
  /** A mask in which the position of each ‘Y’ character indicates each valid length that the reference number can take.At least one ‘Y’ character will be present */
  lengthMask?: string;
  /** This describes which, if any, fixed digits that are standard in the BPAY Customer Reference Number */
  fixedDigits?: string;
  /** Indicates whether BPAY Customer Reference Numbers (CRN) for this billerchanges for each individual customer’s bill or do they remain the same.Non variable CRNs can be stored and used later, however they must always be validated as part of paying a bill via the gateway.Variable CRNs should not be stored as they are incorrect for subsequent bills. */
  isVariableCrn?: boolean;
}

export const dTOBPAYBillerV1Schema: Schema<DTOBPAYBillerV1> = object({
  billerCode: ['billerCode', optional(string())],
  billerLongName: ['billerLongName', optional(string())],
  billerShortName: ['billerShortName', optional(string())],
  acceptedPaymentMethods: ['acceptedPaymentMethods', optional(string())],
  activationDate: ['activationDate', optional(string())],
  deactivationDate: ['deactivationDate', optional(string())],
  minPaymentAmount: ['minPaymentAmount', optional(number())],
  maxPaymentAmount: ['maxPaymentAmount', optional(number())],
  crnValidationRuleName: ['crnValidationRuleName', optional(string())],
  checkDigitRuleName: ['checkDigitRuleName', optional(string())],
  lengthMask: ['lengthMask', optional(string())],
  fixedDigits: ['fixedDigits', optional(string())],
  isVariableCrn: ['isVariableCrn', optional(boolean())],
});
