/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  DTOGenericPaymentGenericPaymentSettlementItemV1,
  dTOGenericPaymentGenericPaymentSettlementItemV1Schema,
} from './dTOGenericPaymentGenericPaymentSettlementItemV1';

export interface DTOGenericPaymentGenericPaymentSettlementResponseV1 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  durationMs?: bigint;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors */
  status?: string;
  /** This is a plain English description of the status. */
  statusDescription?: string;
  /** An array of SettlementItem’s */
  settlements?: DTOGenericPaymentGenericPaymentSettlementItemV1[];
}

export const dTOGenericPaymentGenericPaymentSettlementResponseV1Schema: Schema<DTOGenericPaymentGenericPaymentSettlementResponseV1> = object(
  {
    durationMs: ['durationMs', optional(bigint())],
    status: ['status', optional(string())],
    statusDescription: ['statusDescription', optional(string())],
    settlements: [
      'settlements',
      optional(
        array(lazy(() => dTOGenericPaymentGenericPaymentSettlementItemV1Schema))
      ),
    ],
  }
);
