/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  DTOGenericPaymentDisbursmentFee,
  dTOGenericPaymentDisbursmentFeeSchema,
} from './dTOGenericPaymentDisbursmentFee';
import {
  DTOGenericPaymentFeeDetail,
  dTOGenericPaymentFeeDetailSchema,
} from './dTOGenericPaymentFeeDetail';

export interface DTOGenericPaymentFeeBreakdown {
  debitFee?: DTOGenericPaymentFeeDetail;
  /** Returns an array for disbursementFee, which is the fee details for each disbursement. */
  disbursementFees?: DTOGenericPaymentDisbursmentFee[];
}

export const dTOGenericPaymentFeeBreakdownSchema: Schema<DTOGenericPaymentFeeBreakdown> = object(
  {
    debitFee: [
      'debitFee',
      optional(lazy(() => dTOGenericPaymentFeeDetailSchema)),
    ],
    disbursementFees: [
      'disbursementFees',
      optional(array(lazy(() => dTOGenericPaymentDisbursmentFeeSchema))),
    ],
  }
);
