/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface DTOGenericPaymentFeeDetail {
  /** The fee amount excluding GST */
  feeAmountExcludingGst?: number;
  /** The GST component of the fee */
  feeAmountGstComponent?: number;
  /** The fee amount including GST */
  feeAmountIncludingGst?: number;
}

export const dTOGenericPaymentFeeDetailSchema: Schema<DTOGenericPaymentFeeDetail> = object(
  {
    feeAmountExcludingGst: ['feeAmountExcludingGst', optional(number())],
    feeAmountGstComponent: ['feeAmountGstComponent', optional(number())],
    feeAmountIncludingGst: ['feeAmountIncludingGst', optional(number())],
  }
);
