/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface DTOGenericPaymentLoadFeeV1 {
  /** The type of Disbursement: mAccount, mWallet, DirectCredit, BPAY, Charity, Sign-In mAccount */
  method?: string;
  /** Type of credit card. Null if method is not CreditCard: Mastercard, Visa, Diners, Amex */
  cardType?: string;
  /** Contains the 16-Digit if the fee is associated to a specific mAccount, otherwise null */
  debitFromMAccount?: string;
  /** The percentage of the amountto be taken as a fee Excluding GST */
  feePercentageExGst?: number;
  /** The fixed amount to be taken as a fee Excluding GST */
  feeFixedExGst?: number;
}

export const dTOGenericPaymentLoadFeeV1Schema: Schema<DTOGenericPaymentLoadFeeV1> = object(
  {
    method: ['method', optional(string())],
    cardType: ['cardType', optional(string())],
    debitFromMAccount: ['debitFromMAccount', optional(string())],
    feePercentageExGst: ['feePercentageExGst', optional(number())],
    feeFixedExGst: ['feeFixedExGst', optional(number())],
  }
);
