/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema } from '../schema';
import {
  DTOGenericPaymentFeeDetail,
  dTOGenericPaymentFeeDetailSchema,
} from './dTOGenericPaymentFeeDetail';

export interface DTOGenericPaymentDisbursmentFee {
  /** This is the index into the Disbursement array that was passed to either financials/v2/transaction/validate or financials/v2/transaction/execute */
  disbursementArrayIndex?: number;
  disbursementFee?: DTOGenericPaymentFeeDetail;
}

export const dTOGenericPaymentDisbursmentFeeSchema: Schema<DTOGenericPaymentDisbursmentFee> = object(
  {
    disbursementArrayIndex: ['disbursementArrayIndex', optional(number())],
    disbursementFee: [
      'disbursementFee',
      optional(lazy(() => dTOGenericPaymentFeeDetailSchema)),
    ],
  }
);
