/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface DTOGenericPaymentGenericPaymentStatementItemV1 {
  /** This is your uniqueReference that was passed in when the transaction was executed */
  uniqueReferenced?: string;
  /** This is the transactionId that was returned when the transaction was executed */
  transactionId?: number;
  /** The date time that the transaction was executed on the Platform Servers. Format is ISO8601 - 2015 -09 - 01T19: 19:58 */
  dateTime?: string;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors. */
  status?: string;
  /** This is the total amount of the transaction what was disbursed */
  totalAmount?: number;
  /** This is the fee amount Excluding GST that has been debited from your mAccount */
  feeAmountExcludingGst?: number;
  /** This is the GST Component of the fee amount that has been debited from your mAccount */
  feeAmountGstComponent?: number;
  /** This is the total fee amount Including GST that has been debited from your mAccount */
  feeAmountIncludingGst?: number;
}

export const dTOGenericPaymentGenericPaymentStatementItemV1Schema: Schema<DTOGenericPaymentGenericPaymentStatementItemV1> = object(
  {
    uniqueReferenced: ['uniqueReferenced', optional(string())],
    transactionId: ['transactionId', optional(number())],
    dateTime: ['dateTime', optional(string())],
    status: ['status', optional(string())],
    totalAmount: ['totalAmount', optional(number())],
    feeAmountExcludingGst: ['feeAmountExcludingGst', optional(number())],
    feeAmountGstComponent: ['feeAmountGstComponent', optional(number())],
    feeAmountIncludingGst: ['feeAmountIncludingGst', optional(number())],
  }
);
