/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  DTOGenericPaymentGenericPaymentStatementItemV1,
  dTOGenericPaymentGenericPaymentStatementItemV1Schema,
} from './dTOGenericPaymentGenericPaymentStatementItemV1';

export interface DTOGenericPaymentGenericPaymentStatementResponseV1 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  durationMs?: bigint;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors */
  status?: string;
  /** This is a plain English description of the status. */
  statusDescription?: string;
  /** An array of TransactionItem’s */
  transactions?: DTOGenericPaymentGenericPaymentStatementItemV1[];
}

export const dTOGenericPaymentGenericPaymentStatementResponseV1Schema: Schema<DTOGenericPaymentGenericPaymentStatementResponseV1> = object(
  {
    durationMs: ['durationMs', optional(bigint())],
    status: ['status', optional(string())],
    statusDescription: ['statusDescription', optional(string())],
    transactions: [
      'transactions',
      optional(
        array(lazy(() => dTOGenericPaymentGenericPaymentStatementItemV1Schema))
      ),
    ],
  }
);
