/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema';
import {
  TransactionStatusEnum,
  transactionStatusEnumSchema,
} from './transactionStatusEnum';

export interface DTOGenericPaymentGatewayTransactionStatusResponseV2 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  durationMs?: bigint;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors. */
  status?: string;
  /** This is a plain English description of the status. */
  statusDescription?: string;
  /** This is the date when the transaction was Completed. */
  completedDate?: string;
  /** This field is filled If transaction type is Credit-Card. */
  creditCardPaymentStatus?: string;
  /** once transaction is dishonoured with the transactionStatus set to 'Dishonoured' and the dishonouredDate has a value. */
  dishonouredDate?: string;
  /** expected clearance date for funds if applicable. */
  expectedClearanceDateForFunds?: string;
  /** clearance date for funds if applicable. "yyyy-MM-dd" format. */
  fundsClearedDate?: string;
  /** The transaction has not yet been dishonoured if the transactionStatus is 'Complete'. &nbsp; The transaction is dishonoured when the transactionStatus is set to 'Dishonoured' and the dishonouredDate has a value. */
  transactionStatus?: TransactionStatusEnum;
  /** This is the unique reference that was passed in by the calling service. */
  uniqueReference?: string;
}

export const dTOGenericPaymentGatewayTransactionStatusResponseV2Schema: Schema<DTOGenericPaymentGatewayTransactionStatusResponseV2> = object(
  {
    durationMs: ['durationMs', optional(bigint())],
    status: ['status', optional(string())],
    statusDescription: ['statusDescription', optional(string())],
    completedDate: ['completedDate', optional(string())],
    creditCardPaymentStatus: ['creditCardPaymentStatus', optional(string())],
    dishonouredDate: ['dishonouredDate', optional(string())],
    expectedClearanceDateForFunds: [
      'expectedClearanceDateForFunds',
      optional(string()),
    ],
    fundsClearedDate: ['fundsClearedDate', optional(string())],
    transactionStatus: [
      'transactionStatus',
      optional(transactionStatusEnumSchema),
    ],
    uniqueReference: ['uniqueReference', optional(string())],
  }
);
