/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, lazy, object, optional, Schema, string } from '../schema';
import { DTOMWalletDetails, dTOMWalletDetailsSchema } from './dTOMWalletDetails';

export interface DTOMWalletUpdateResponseV1 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  durationMs?: bigint;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors */
  status?: string;
  /** This is a plain English description of the status. */
  statusDescription?: string;
  mWallet?: DTOMWalletDetails;
}

export const dTOMWalletUpdateResponseV1Schema: Schema<DTOMWalletUpdateResponseV1> = object(
  {
    durationMs: ['durationMs', optional(bigint())],
    status: ['status', optional(string())],
    statusDescription: ['statusDescription', optional(string())],
    mWallet: ['mWallet', optional(lazy(() => dTOMWalletDetailsSchema))],
  }
);
