/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface DTOMWalletFinancials {
  /** Current remaining balance on the mWalletaccount */
  actualBalance?: number;
  /** The amount of funds that can be debited from the mWallet */
  availableSpend?: number;
  /** The amount of funds that can be credited to the mWallet */
  availableLoad?: number;
}

export const dTOMWalletFinancialsSchema: Schema<DTOMWalletFinancials> = object({
  actualBalance: ['actualBalance', optional(number())],
  availableSpend: ['availableSpend', optional(number())],
  availableLoad: ['availableLoad', optional(number())],
});
