/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface DTOMAccountClearedFundsAccount {
  /** available funds */
  availableBalance?: number;
  /** on hold funds from Direct Debit transaction */
  unclearedFunds?: number;
  /** an list of cleardsfunds transaction that is waiting to clear */
  uniqueReferencesWaitingToClear?: string[];
}

export const dTOMAccountClearedFundsAccountSchema: Schema<DTOMAccountClearedFundsAccount> = object(
  {
    availableBalance: ['availableBalance', optional(number())],
    unclearedFunds: ['unclearedFunds', optional(number())],
    uniqueReferencesWaitingToClear: [
      'uniqueReferencesWaitingToClear',
      optional(array(string())),
    ],
  }
);
