/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, bigint, object, optional, Schema, string } from '../schema';

export interface DTOMAccountListResponseV1 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  durationMs?: bigint;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors */
  status?: string;
  /** This is a plain English description of the status. */
  statusDescription?: string;
  /** Array of 16-Digit account numbers */
  mAccounts?: string[];
}

export const dTOMAccountListResponseV1Schema: Schema<DTOMAccountListResponseV1> = object(
  {
    durationMs: ['durationMs', optional(bigint())],
    status: ['status', optional(string())],
    statusDescription: ['statusDescription', optional(string())],
    mAccounts: ['mAccounts', optional(array(string()))],
  }
);
