/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Key10Enum, key10EnumSchema } from './key10Enum';

export interface DTOMWalletOptionItem {
  /** Unique identifier of the value. */
  key?: Key10Enum;
  /** The actual value represented by the Key */
  value?: string;
}

export const dTOMWalletOptionItemSchema: Schema<DTOMWalletOptionItem> = object({
  key: ['key', optional(key10EnumSchema)],
  value: ['value', optional(string())],
});
