/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  DTOMAccountClearedFundsAccount,
  dTOMAccountClearedFundsAccountSchema,
} from './dTOMAccountClearedFundsAccount';

export interface DTOMAccountFinancials {
  /** 16 digit mAccount Number */
  accountNumber?: number;
  /** Balance of the mAccount */
  actualBalance?: number;
  /** Whether mAccount is cleared funds */
  clearedFundsOnly?: boolean;
  /** mAccount credit limit */
  creditLimit?: number;
  /** Balance of the feeAccount */
  feeAccountActualBalance?: number;
  /** 16 digit feeAccount number (returns value if hasSeparateFeeAccount is 'true') */
  feeAccountNumber?: number;
  /** Whether mAccount has SeparateFeeAccount */
  hasSeparateFeeAccount?: boolean;
  /** mAccount lower credit limit */
  lowerCreditLimit?: number;
  /** mAccount minimum SettlementAmount. minimum value is '0.02' */
  minimumSettlementAmount?: number;
  /** mAccount settlement frequency */
  settlementFrequency?: string;
  /** mAccount upper credit limit */
  upperCreditLimit?: number;
  /** whether mAccount is fee account */
  isFeeAccount?: boolean;
  /** whether mAccount is parent account */
  isParentAccount?: boolean;
  /** whether mAccount is parent account */
  isParentClearedFunds?: boolean;
  clearedFundsAccountFinancials?: DTOMAccountClearedFundsAccount;
}

export const dTOMAccountFinancialsSchema: Schema<DTOMAccountFinancials> = object(
  {
    accountNumber: ['accountNumber', optional(number())],
    actualBalance: ['actualBalance', optional(number())],
    clearedFundsOnly: ['clearedFundsOnly', optional(boolean())],
    creditLimit: ['creditLimit', optional(number())],
    feeAccountActualBalance: ['feeAccountActualBalance', optional(number())],
    feeAccountNumber: ['feeAccountNumber', optional(number())],
    hasSeparateFeeAccount: ['hasSeparateFeeAccount', optional(boolean())],
    lowerCreditLimit: ['lowerCreditLimit', optional(number())],
    minimumSettlementAmount: ['minimumSettlementAmount', optional(number())],
    settlementFrequency: ['settlementFrequency', optional(string())],
    upperCreditLimit: ['upperCreditLimit', optional(number())],
    isFeeAccount: ['isFeeAccount', optional(boolean())],
    isParentAccount: ['isParentAccount', optional(boolean())],
    isParentClearedFunds: ['isParentClearedFunds', optional(boolean())],
    clearedFundsAccountFinancials: [
      'clearedFundsAccountFinancials',
      optional(lazy(() => dTOMAccountClearedFundsAccountSchema)),
    ],
  }
);
