/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  DTOMWalletFinancials,
  dTOMWalletFinancialsSchema,
} from './dTOMWalletFinancials';
import {
  DTOMWalletOptionItem,
  dTOMWalletOptionItemSchema,
} from './dTOMWalletOptionItem';

export interface DTOMWalletDetails {
  /** Date that this customer was created.ISO 8601 date-time format.Note that Timezone is suppressed.The example Timezone is Sydney local time */
  createdDateTime?: string;
  /** 16-Digit account number that uniquely identifies the customer */
  accountNumber?: string;
  /** Customers full name */
  name?: string;
  /** This is a short form name of the customer */
  nickName?: string;
  /** Email address of the customer */
  email?: string;
  /** Mobile phone number of the customer */
  mobile?: string;
  /** Date of the last transaction that the customer performed. ISO 8601 date format. This is an empty string if no transactions.Note that Timezone is suppressed.The example Timezone is Sydney local time */
  lastTransactionDate?: string;
  /** Contact phone number for customer. Can be a mobile or landline */
  contactPhone?: string;
  /** Unique email address used to authenticate customer. Can be null */
  authenticationEmail?: string;
  /** Unique mobile number used to authenticate customer. Can be null */
  authenticationMobile?: string;
  /** Unique telephone number used to authenticate customer. Can be null */
  authenticationLandLine?: string;
  /** 16-Digit account number of the mAccount who created the customer */
  registeredByMAccountNumber?: string;
  /** The customer’s account has been put on hold */
  isOnHold?: boolean;
  /** The customer’s account has been closed */
  isClosed?: boolean;
  isStolen?: boolean;
  /** The mWallet is registered and is able to purchase restricted itemsfrom the mAccount such as BPAY */
  isRegistered?: boolean;
  financials?: DTOMWalletFinancials;
  /** mWalletOptionItem */
  options?: DTOMWalletOptionItem[];
}

export const dTOMWalletDetailsSchema: Schema<DTOMWalletDetails> = object({
  createdDateTime: ['createdDateTime', optional(string())],
  accountNumber: ['accountNumber', optional(string())],
  name: ['name', optional(string())],
  nickName: ['nickName', optional(string())],
  email: ['email', optional(string())],
  mobile: ['mobile', optional(string())],
  lastTransactionDate: ['lastTransactionDate', optional(string())],
  contactPhone: ['contactPhone', optional(string())],
  authenticationEmail: ['authenticationEmail', optional(string())],
  authenticationMobile: ['authenticationMobile', optional(string())],
  authenticationLandLine: ['authenticationLandLine', optional(string())],
  registeredByMAccountNumber: [
    'registeredByMAccountNumber',
    optional(string()),
  ],
  isOnHold: ['isOnHold', optional(boolean())],
  isClosed: ['isClosed', optional(boolean())],
  isStolen: ['isStolen', optional(boolean())],
  isRegistered: ['isRegistered', optional(boolean())],
  financials: ['financials', optional(lazy(() => dTOMWalletFinancialsSchema))],
  options: ['options', optional(array(lazy(() => dTOMWalletOptionItemSchema)))],
});
