/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  DTOMAccountFinancials,
  dTOMAccountFinancialsSchema,
} from './dTOMAccountFinancials';
import { DTOOptionItem, dTOOptionItemSchema } from './dTOOptionItem';

export interface DTOMAccountDetails {
  /** 16-Digit account number that uniquely identifies the mAccount */
  accountNumber?: bigint;
  /** Company name of the mAccount */
  name?: string;
  /** Company ABN of the mAccount. All non numbers are stripped */
  abn?: string;
  /** Contact name. Spaces are stripped */
  contactName?: string;
  /** Contact number. All non numbers are striped */
  contactNumber?: string;
  /** Contact email. Converted to lowercase */
  email?: string;
  /** An optional postal addressline such as a Building, section or unit */
  addressLine1?: string;
  /** An address line is the main postal address of the Company */
  addressLine2?: string;
  /** Postal address suburb */
  suburb?: string;
  /** Postal addres sstate */
  state?: string;
  /** Postal address post code */
  postCode?: string;
  /** BSB number of associated bank account. BSB format is ‘000-000’ */
  bsb?: string;
  /** Bank account number of associated bank account */
  bankAccountNumber?: number;
  /** Bank account title or nameof associated bank account */
  bankAccountTitle?: string;
  /** If true, allow the creation of a new mAccount even though an existing mAccount with the same ABN exists */
  allowDuplicates?: boolean;
  feeAccount?: number;
  financials?: DTOMAccountFinancials;
  /** an Array of mAccountOptionItem */
  options?: DTOOptionItem[];
}

export const dTOMAccountDetailsSchema: Schema<DTOMAccountDetails> = object({
  accountNumber: ['accountNumber', optional(bigint())],
  name: ['name', optional(string())],
  abn: ['abn', optional(string())],
  contactName: ['contactName', optional(string())],
  contactNumber: ['contactNumber', optional(string())],
  email: ['email', optional(string())],
  addressLine1: ['addressLine1', optional(string())],
  addressLine2: ['addressLine2', optional(string())],
  suburb: ['suburb', optional(string())],
  state: ['state', optional(string())],
  postCode: ['postCode', optional(string())],
  bsb: ['bsb', optional(string())],
  bankAccountNumber: ['bankAccountNumber', optional(number())],
  bankAccountTitle: ['bankAccountTitle', optional(string())],
  allowDuplicates: ['allowDuplicates', optional(boolean())],
  feeAccount: ['feeAccount', optional(number())],
  financials: ['financials', optional(lazy(() => dTOMAccountFinancialsSchema))],
  options: ['options', optional(array(lazy(() => dTOOptionItemSchema)))],
});
