/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, boolean, object, optional, Schema, string } from '../schema';

export interface DTOToolsAbnValidateResponseV1 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  durationMs?: bigint;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors */
  status?: string;
  /** This is a plain English description of the status. */
  statusDescription?: string;
  /** The Australian Business Number that was passed as aparameter formatted as ’99 999 999 999’ */
  abn?: string;
  /** The date the ABN record was last updated */
  lastUpdatedDate?: string;
  /** If true, indicates the identity has a valid ABN */
  isAbnValid?: boolean;
  /** If true, indicates the identity is a registered charity */
  isCharity?: boolean;
  /** The abbreviation of the type of business entity */
  entityTypeCode?: string;
  /** A description the type of business entity */
  entityTypeDescription?: string;
  /** The current name of the business entity */
  organisationName?: string;
  /** If business is a Sole Trader, contains the persons name */
  legalName?: string;
  /** The date the organisationName was last updated */
  organisationNameFromDate?: string;
  /** The state code of the business physical address – eg. ‘NSW’ */
  businessPhysicalAddressStateCode?: string;
  /** The post code of the business physical address */
  businessPhysicalAddressPostCode?: string;
  /** The date the business physical address was last updated */
  businessPhysicalAddressEffectiveFromDate?: string;
}

export const dTOToolsAbnValidateResponseV1Schema: Schema<DTOToolsAbnValidateResponseV1> = object(
  {
    durationMs: ['durationMs', optional(bigint())],
    status: ['status', optional(string())],
    statusDescription: ['statusDescription', optional(string())],
    abn: ['abn', optional(string())],
    lastUpdatedDate: ['lastUpdatedDate', optional(string())],
    isAbnValid: ['isAbnValid', optional(boolean())],
    isCharity: ['isCharity', optional(boolean())],
    entityTypeCode: ['entityTypeCode', optional(string())],
    entityTypeDescription: ['entityTypeDescription', optional(string())],
    organisationName: ['organisationName', optional(string())],
    legalName: ['legalName', optional(string())],
    organisationNameFromDate: ['organisationNameFromDate', optional(string())],
    businessPhysicalAddressStateCode: [
      'businessPhysicalAddressStateCode',
      optional(string()),
    ],
    businessPhysicalAddressPostCode: [
      'businessPhysicalAddressPostCode',
      optional(string()),
    ],
    businessPhysicalAddressEffectiveFromDate: [
      'businessPhysicalAddressEffectiveFromDate',
      optional(string()),
    ],
  }
);
