/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, boolean, object, optional, Schema, string } from '../schema';

export interface DTOToolsBsbValidateResponseV1 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  durationMs?: bigint;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors */
  status?: string;
  /** This is a plain English description of the status. */
  statusDescription?: string;
  /** The BSBNumber that was passed as a parameter */
  bsb?: string;
  /** Indicates if the branch has been closed. If true, the address field MAY contain a reference to a replacement BSB number */
  closed?: boolean;
  /** The branch address */
  address?: string;
  /** The branch city */
  city?: string;
  /** The branch state e.g. NSW, VIC, QLD etc */
  state?: string;
  /** The branch post code */
  postCode?: string;
  /** The bank code e.g.ANZ, CBA, NAB, WBC etc */
  bankCode?: string;
}

export const dTOToolsBsbValidateResponseV1Schema: Schema<DTOToolsBsbValidateResponseV1> = object(
  {
    durationMs: ['durationMs', optional(bigint())],
    status: ['status', optional(string())],
    statusDescription: ['statusDescription', optional(string())],
    bsb: ['bsb', optional(string())],
    closed: ['closed', optional(boolean())],
    address: ['address', optional(string())],
    city: ['city', optional(string())],
    state: ['state', optional(string())],
    postCode: ['postCode', optional(string())],
    bankCode: ['bankCode', optional(string())],
  }
);
