/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema';

export interface DTOTokenGetResponseV1 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  durationMs?: bigint;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors */
  status?: string;
  /** This is a plain English description of the status. */
  statusDescription?: string;
  /** The text (GUID) that identifies the token */
  token?: string;
  /** Text that gives sufficient information to allow the tokento be selected but does not compromise security */
  hint?: string;
  /** BPAY or AustralianBankAccount */
  payloadType?: string;
  /** Text supplied when the tokenwas created */
  description?: string;
}

export const dTOTokenGetResponseV1Schema: Schema<DTOTokenGetResponseV1> = object(
  {
    durationMs: ['durationMs', optional(bigint())],
    status: ['status', optional(string())],
    statusDescription: ['statusDescription', optional(string())],
    token: ['token', optional(string())],
    hint: ['hint', optional(string())],
    payloadType: ['payloadType', optional(string())],
    description: ['description', optional(string())],
  }
);
