/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for EventName1Enum
 */
export enum EventName1Enum {
  NPPReceivePayment = 'NPPReceivePayment',
  InboundDirectCredit = 'InboundDirectCredit',
  InboundDirectDebit = 'InboundDirectDebit',
  DirectEntryDishonour = 'DirectEntryDishonour',
}

/**
 * Schema for EventName1Enum
 */
export const eventName1EnumSchema: Schema<EventName1Enum> = stringEnum(EventName1Enum);
