/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { BankDetails, bankDetailsSchema } from './bankDetails';

export interface EventDirectEntryDishonoursWebhook {
  /** Return Date. */
  returnDate?: string;
  /** Total Amount. */
  amount?: number;
  bankDetails?: BankDetails;
  /** Value will be either Credit or Debit. */
  type?: string;
  /** Return Reason Text. */
  returnReason?: string;
  /** Original Transaction Date. */
  transactionDate?: string;
  /** Original Transaction Id. */
  originalTransactionId?: number;
  /** Client UniqueReference, generated by the calling service. */
  transactionReference?: string;
}

export const eventDirectEntryDishonoursWebhookSchema: Schema<EventDirectEntryDishonoursWebhook> = object(
  {
    returnDate: ['ReturnDate', optional(string())],
    amount: ['Amount', optional(number())],
    bankDetails: ['BankDetails', optional(lazy(() => bankDetailsSchema))],
    type: ['Type', optional(string())],
    returnReason: ['ReturnReason', optional(string())],
    transactionDate: ['TransactionDate', optional(string())],
    originalTransactionId: ['OriginalTransactionId', optional(number())],
    transactionReference: ['TransactionReference', optional(string())],
  }
);
