/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import { PayIdType1Enum, payIdType1EnumSchema } from './payIdType1Enum';

export interface EventNppPaymentStatusWebhook {
  /** Transaction Date. */
  transactionDate?: string;
  /** Client UniqueReference, generated by the calling service. */
  uniqueReference?: string;
  /** Monoova Transaction Id. */
  transactionId?: number;
  /** Transaction Status. */
  status?: string;
  /** Amount. */
  amount?: number;
  /** Payee BSB. */
  bsb?: string;
  /** Payee Bank Account Number. */
  accountNumber?: string;
  /** Payee Account Name. */
  accountName?: string;
  /** PayId Identifier of the Payee. */
  payId?: string;
  /** PayId Type. Possible values:&nbsp; ABN, Email, PhoneNumber, OrganisationId, ACN */
  payIdType?: PayIdType1Enum;
  /** End to End identifier submitted by Payer. */
  endToEndId?: string;
  /** Original Remitting Entity. */
  remitterName?: string;
  /** Original Payment reference. */
  lodgementRef?: string;
  /** Rejection Date Time. */
  rejectionDateTime?: string;
  /** Rejection reason description. */
  rejectionReasonDescription?: string;
  /** Rejection Transaction Id. */
  rejectionTransactionId?: number;
}

export const eventNppPaymentStatusWebhookSchema: Schema<EventNppPaymentStatusWebhook> = object(
  {
    transactionDate: ['TransactionDate', optional(string())],
    uniqueReference: ['UniqueReference', optional(string())],
    transactionId: ['TransactionId', optional(number())],
    status: ['Status', optional(string())],
    amount: ['Amount', optional(number())],
    bsb: ['Bsb', optional(string())],
    accountNumber: ['AccountNumber', optional(string())],
    accountName: ['AccountName', optional(string())],
    payId: ['PayId', optional(string())],
    payIdType: ['PayIdType', optional(payIdType1EnumSchema)],
    endToEndId: ['EndToEndId', optional(string())],
    remitterName: ['RemitterName', optional(string())],
    lodgementRef: ['LodgementRef', optional(string())],
    rejectionDateTime: ['RejectionDateTime', optional(string())],
    rejectionReasonDescription: [
      'RejectionReasonDescription',
      optional(string()),
    ],
    rejectionTransactionId: ['RejectionTransactionId', optional(number())],
  }
);
