/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for EventNameEnum
 */
export enum EventNameEnum {
  NppReturn = 'NppReturn',
  NppPaymentStatus = 'NppPaymentStatus',
  PayToReceivePayment = 'PayToReceivePayment',
  NPPReceivePayment = 'NPPReceivePayment',
  InboundDirectCredit = 'InboundDirectCredit',
  InboundDirectDebit = 'InboundDirectDebit',
  DirectEntryDishonour = 'DirectEntryDishonour',
  PendingInboundRtgsImt = 'PendingInboundRtgsImt',
  InboundRtgsImtStatus = 'InboundRtgsImtStatus',
}

/**
 * Schema for EventNameEnum
 */
export const eventNameEnumSchema: Schema<EventNameEnum> = stringEnum(EventNameEnum);
