/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface EventPayToreceivePaymentWebhook {
  /** Monoova generated Unique ID. */
  transactionId?: string;
  /** Time Stamp. */
  dateTime?: string;
  /** Remitting Entity. */
  remitterName?: string;
  /** Payment amount, 2 decimal places for cents. */
  amount?: string;
  /** Payer submitted Account Name. */
  accountName?: string;
  /** Payee Bank Account Number. */
  accountNumber?: string;
  /** Payee BSB. */
  bsb?: string;
  /** This is the Payment description provided by the Payer and is equivalent to the lodgementReference field in Direct Entry. It accepts UTF-8 character set. */
  paymentDescription?: string;
  /** Email address for the PayID. */
  payId?: string;
  /** PayID Name. */
  payIdName?: string;
  /** Payer BSB. */
  sourceBsb?: string;
  /** Payer Bank Account Number. */
  sourceAccountNumber?: string;
  /** This field appears for NPP transactions only and is the payers bank account name. For DE transactions please refer to the  RemitterName Field. */
  sourceAccountName?: string;
  /** Osko End to End identifier submitted by Payer. */
  endToEndId?: string;
  /** NPP payment purpose code. Possible values are Blank, SALA, PENS, SUPP, TAXS */
  categoryPurposeCode?: string;
  /** Used for SALA, PENS, SUPP and TAXS transactions only. Reference related to payment type. */
  creditorReferenceInformation?: string;
  /** Used for PENS code payments only. Unique Superannuation ID (USI). */
  uSINumber?: string;
  /** Used for PENS code payments only. USI scheme. */
  uSIScheme?: string;
  /** Used for PENS code payments only. Name of the Ultimate Creditor. */
  ultimateCreditorName?: string;
  mmsId?: string;
  /** Iniation Party name.. */
  initiatingPartyName?: string;
}

export const eventPayToreceivePaymentWebhookSchema: Schema<EventPayToreceivePaymentWebhook> = object(
  {
    transactionId: ['TransactionId', optional(string())],
    dateTime: ['DateTime', optional(string())],
    remitterName: ['RemitterName', optional(string())],
    amount: ['Amount', optional(string())],
    accountName: ['AccountName', optional(string())],
    accountNumber: ['AccountNumber', optional(string())],
    bsb: ['Bsb', optional(string())],
    paymentDescription: ['PaymentDescription', optional(string())],
    payId: ['payId', optional(string())],
    payIdName: ['payIdName', optional(string())],
    sourceBsb: ['SourceBsb', optional(string())],
    sourceAccountNumber: ['SourceAccountNumber', optional(string())],
    sourceAccountName: ['SourceAccountName', optional(string())],
    endToEndId: ['EndToEndId', optional(string())],
    categoryPurposeCode: ['CategoryPurposeCode', optional(string())],
    creditorReferenceInformation: [
      'CreditorReferenceInformation',
      optional(string()),
    ],
    uSINumber: ['USINumber', optional(string())],
    uSIScheme: ['USIScheme', optional(string())],
    ultimateCreditorName: ['UltimateCreditorName', optional(string())],
    mmsId: ['mmsId', optional(string())],
    initiatingPartyName: ['InitiatingPartyName', optional(string())],
  }
);
