/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface FinancialTransaction {
  /**
   * This is a unique reference generated by the calling service.
   * This is a nonce. Its use is to determine if a request has already been received by the Engine.
   * We strongly recommend sending a uniqueReference in your execution call to avoid duplicate transactions.
   */
  uniqueReference?: string;
  /** If true, the uniqueReference will be printed on the statement. Default is false. */
  printUniqueReferenceOnStatement?: boolean;
  /** This is the total amount of the transaction */
  totalAmount?: number;
  paymentSource?: string;
}

export const financialTransactionSchema: Schema<FinancialTransaction> = object({
  uniqueReference: ['uniqueReference', optional(string())],
  printUniqueReferenceOnStatement: [
    'printUniqueReferenceOnStatement',
    optional(boolean()),
  ],
  totalAmount: ['totalAmount', optional(number())],
  paymentSource: ['paymentSource', optional(string())],
});
