/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FrequencyEnum
 */
export enum FrequencyEnum {
  Custom = 'Custom',
  ThisMonth = 'ThisMonth',
  LastMonth = 'LastMonth',
  Today = 'Today',
}

/**
 * Schema for FrequencyEnum
 */
export const frequencyEnumSchema: Schema<FrequencyEnum> = stringEnum(FrequencyEnum);
