/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface InboundDirectCreditWebhookDirectCreditDetails {
  /** Monoova generated Unique ID. */
  transactionId?: string;
  /** Payment Batch ID. Payments come in batches throughout the day. */
  batchId?: string;
  /** Time Stamp. */
  dateTime?: string;
  /** Payee BSB. */
  bsb?: string;
  /** Payee Bank Account Number. */
  accountNumber?: number;
  /** Payer submitted Account Name. */
  accountName?: string;
  /** Externally initiated credit items with the exception of those bearing Transaction Codes. */
  transactionCode?: string;
  /** Payment amount, 2 decimal places for cents. */
  amount?: number;
  /** Payer submitted reference. */
  lodgementRef?: string;
  /** Remitting Entity. */
  remitterName?: string;
  /** Preferred name of the User supplying the Direct Entry file. */
  nameOfUserSupplyingFile?: string;
  /** This is the User Identification Number which is assigned by APCA and User Financial Institutions. */
  numberOfUserSupplyingFile?: string;
  /** Direct Entry file description. */
  descriptionOfEntriesOnFile?: string;
  /** Blank; OR 'W' dividend paid to a resident of a country where a double tax agreement is in force. 'X' dividend paid to a resident of any other country. 'Y' interest paid to all non-resident. */
  indicator?: string;
  /** Blank OR Payment amount,2 decimal places for cents. */
  withholdingTaxAmount?: number;
  /** Payer BSB. */
  sourceBsb?: string;
  /** Payer Bank Account Number. */
  sourceAccountNumber?: string;
}

export const inboundDirectCreditWebhookDirectCreditDetailsSchema: Schema<InboundDirectCreditWebhookDirectCreditDetails> = object(
  {
    transactionId: ['TransactionId', optional(string())],
    batchId: ['BatchId', optional(string())],
    dateTime: ['DateTime', optional(string())],
    bsb: ['Bsb', optional(string())],
    accountNumber: ['AccountNumber', optional(number())],
    accountName: ['AccountName', optional(string())],
    transactionCode: ['TransactionCode', optional(string())],
    amount: ['Amount', optional(number())],
    lodgementRef: ['LodgementRef', optional(string())],
    remitterName: ['RemitterName', optional(string())],
    nameOfUserSupplyingFile: ['NameOfUserSupplyingFile', optional(string())],
    numberOfUserSupplyingFile: [
      'NumberOfUserSupplyingFile',
      optional(string()),
    ],
    descriptionOfEntriesOnFile: [
      'DescriptionOfEntriesOnFile',
      optional(string()),
    ],
    indicator: ['Indicator', optional(string())],
    withholdingTaxAmount: ['WithholdingTaxAmount', optional(number())],
    sourceBsb: ['SourceBsb', optional(string())],
    sourceAccountNumber: ['SourceAccountNumber', optional(string())],
  }
);
