/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Key10Enum
 */
export enum Key10Enum {
  MobileForSms = 'MobileForSms',
}

/**
 * Schema for Key10Enum
 */
export const key10EnumSchema: Schema<Key10Enum> = stringEnum(Key10Enum);
