/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Key1Enum
 */
export enum Key1Enum {
  DebitTplusXDays = 'DebitTplusXDays',
}

/**
 * Schema for Key1Enum
 */
export const key1EnumSchema: Schema<Key1Enum> = stringEnum(Key1Enum);
