/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Key3Enum
 */
export enum Key3Enum {
  SettlementFrequency = 'SettlementFrequency',
}

/**
 * Schema for Key3Enum
 */
export const key3EnumSchema: Schema<Key3Enum> = stringEnum(Key3Enum);
