/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Key4Enum
 */
export enum Key4Enum {
  SendSettlementStatement = 'SendSettlementStatement',
}

/**
 * Schema for Key4Enum
 */
export const key4EnumSchema: Schema<Key4Enum> = stringEnum(Key4Enum);
