/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Key5Enum
 */
export enum Key5Enum {
  SendDailyStatement = 'SendDailyStatement',
}

/**
 * Schema for Key5Enum
 */
export const key5EnumSchema: Schema<Key5Enum> = stringEnum(Key5Enum);
