/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Key6Enum
 */
export enum Key6Enum {
  SendMonthlyStatement = 'SendMonthlyStatement',
}

/**
 * Schema for Key6Enum
 */
export const key6EnumSchema: Schema<Key6Enum> = stringEnum(Key6Enum);
