/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for KeyEnum
 */
export enum KeyEnum {
  MinimumSettlementAmount = 'MinimumSettlementAmount',
}

/**
 * Schema for KeyEnum
 */
export const keyEnumSchema: Schema<KeyEnum> = stringEnum(KeyEnum);
