/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** disbursement to mAccount */
export interface MAccount {
  disbursementMethod: string;
  /** description for the transaction */
  description?: string;
  /** 16-Digit account number that uniquely identifies the mAccount */
  toMAccount: string;
  /** This is the amount of funds to be paid */
  amount: number;
}

export const mAccountSchema: Schema<MAccount> = object({
  disbursementMethod: ['disbursementMethod', string()],
  description: ['description', optional(string())],
  toMAccount: ['toMAccount', string()],
  amount: ['amount', number()],
});
