/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';
import { FrequencyEnum, frequencyEnumSchema } from './frequencyEnum';

export interface MAccountTransactions {
  /** 16-Digit account number that uniquely identifies the mAccount. */
  accountNumber: string;
  /** An enumeration of fixed selection types. possible values:&nbsp; Today, ThisMonth, LastMonth, Custom. A maximum of 3 months can be retrieved through Frequency = “Custom” */
  frequency: FrequencyEnum;
  /** Start date of statement when the frequency is set to custom. In ISO 8601 date-time format '2018-07-11T00:00:00'. Note that Timezone is suppressed. The default Timezone is Sydney local time. Required field when frequency is set to custom. */
  startDate?: string;
  /** End date of statement when the frequency is set to custom. In ISO 8601 date-time format 2018-08-11T00:00:00' . Note that Timezone is suppressed. The default Timezone is Sydney local time. Required field when frequency is set to custom. */
  endDate?: string;
  /** Default to false. true to sort the returned transaction list as descending order. */
  descending?: boolean;
  /** Default to false. true to use startDate and endDate when the frequency is set to custom. */
  useTime?: boolean;
}

export const mAccountTransactionsSchema: Schema<MAccountTransactions> = object({
  accountNumber: ['accountNumber', string()],
  frequency: ['frequency', frequencyEnumSchema],
  startDate: ['startDate', optional(string())],
  endDate: ['endDate', optional(string())],
  descending: ['descending', optional(boolean())],
  useTime: ['useTime', optional(boolean())],
});
