/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface MAccountSendStatement {
  /** The 16-Digit account number that uniquely identifies the mAccount. */
  accountNumber: string;
  /** An enumeration of fixed selection types. <strong> All, Today, ThisMonth, LastMonth, ThisFinancialYear, LastFinancialYear, Custom </strong> */
  frequency: string;
  /** Start date of statement when the frequency is set to custom. In ISO 8601 date-time format. Note that Timezone is suppressed. The default Timezone is Sydney local time. Required field when frequency is set to custom. */
  startDate?: string;
  /** End date of statement when the frequency is set to custom. In ISO 8601 date-time format. Note that Timezone is suppressed. The default Timezone is Sydney local time. Required field when frequency is set to custom. */
  endDate?: string;
}

export const mAccountSendStatementSchema: Schema<MAccountSendStatement> = object(
  {
    accountNumber: ['accountNumber', string()],
    frequency: ['frequency', string()],
    startDate: ['startDate', optional(string())],
    endDate: ['endDate', optional(string())],
  }
);
