/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import { KeyEnum, keyEnumSchema } from './keyEnum';

export interface MinimumSettlementAmount {
  key?: KeyEnum;
  value?: number;
}

export const minimumSettlementAmountSchema: Schema<MinimumSettlementAmount> = object(
  {
    key: ['key', optional(keyEnumSchema)],
    value: ['value', optional(number())],
  }
);
