/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import { Key9Enum, key9EnumSchema } from './key9Enum';
import { Value3Enum, value3EnumSchema } from './value3Enum';

export interface MobileForSms {
  /** Unique identifier of the value.  this is to use for receiving SMS notifications. */
  key?: Key9Enum;
  /** The actual value represented by the Key. */
  value?: Value3Enum;
}

export const mobileForSmsSchema: Schema<MobileForSms> = object({
  key: ['key', optional(key9EnumSchema)],
  value: ['value', optional(value3EnumSchema)],
});
