/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface MWalletResetPin {
  /** The 16-Digit mWallet account number to reset. */
  accountNumber: string;
  /** 4 digit numerical pin. */
  pin: number;
  /** Birth date of customer or require field in ISO 8601 date-time format. Note that Timezone is suppressed. The default Timezone is Sydney local time. */
  dateOfBirth: string;
}

export const mWalletResetPinSchema: Schema<MWalletResetPin> = object({
  accountNumber: ['accountNumber', string()],
  pin: ['pin', number()],
  dateOfBirth: ['dateOfBirth', string()],
});
