/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { MobileForSms, mobileForSmsSchema } from './mobileForSms';

export interface MWalletUpdate {
  /** 16-Digit mWallet account number to update. */
  accountNumber: string;
  /** 4 digit numerical pin. */
  pin: number;
  /** Full name of customer. */
  name: string;
  /** This is a short form name of the customer. Can be empty */
  nickName?: string;
  /** Contact phone number. This is not used for authentication. Required field in conjunction with email address that must start with 0. All non-numbers are stripped. */
  phone?: number;
  /** Contact email. This is not used for authentication. Limited to 300 characters. Required field in conjunction with phone and should contain @ and follow normal email format conventions. Converted to lowercase. */
  email?: string;
  /** Company ABN of the mAccount. All non numbers are stripped */
  abn?: string;
  options?: MobileForSms[];
}

export const mWalletUpdateSchema: Schema<MWalletUpdate> = object({
  accountNumber: ['accountNumber', string()],
  pin: ['pin', number()],
  name: ['name', string()],
  nickName: ['nickName', optional(string())],
  phone: ['phone', optional(number())],
  email: ['email', optional(string())],
  abn: ['abn', optional(string())],
  options: ['options', optional(array(lazy(() => mobileForSmsSchema)))],
});
