/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface MWalletTransactions {
  /** The 16-Digit account number that uniquely identifies the mWallet. */
  accountNumber: string;
  /** 4 digit numerical pin. */
  pin: number;
  /** Start date of statement when the frequency is set to custom. In ISO 8601 date-time format. Note that Timezone is suppressed. The default Timezone is Sydney local time. Required field when frequency is set to custom. */
  startDate?: string;
  /** End date of statement when the frequency is set to custom. In ISO 8601 date-time format. Note that Timezone is suppressed. The default Timezone is Sydney local time. Required field when frequency is set to custom. */
  endDate?: string;
  /** Number of records to skip. 0 is the first record. */
  skip?: number;
  /** Number of records to take. If take is 0 the all records will be returned. */
  take?: number;
  /** Sort the returned transaction list ascending or descending. */
  descending?: boolean;
  /** Use the time component of startDate and endDate in the selection. */
  useTime?: boolean;
}

export const mWalletTransactionsSchema: Schema<MWalletTransactions> = object({
  accountNumber: ['accountNumber', string()],
  pin: ['pin', number()],
  startDate: ['startDate', optional(string())],
  endDate: ['endDate', optional(string())],
  skip: ['skip', optional(number())],
  take: ['take', optional(number())],
  descending: ['descending', optional(boolean())],
  useTime: ['useTime', optional(boolean())],
});
