/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import { EventName1Enum, eventName1EnumSchema } from './eventName1Enum';
import { Status1Enum, status1EnumSchema } from './status1Enum';

export interface NotificationResponse {
  /** Date time the subscription was last updated */
  dateTime?: string;
  /** The type of event to be sent to this URL via callback. */
  eventName?: EventName1Enum;
  /** last response code received */
  lastResponseCode?: number;
  /** Date time the last retry was done */
  lastRetryDateTime?: string;
  /** Number of retry */
  retryCount?: number;
  status?: Status1Enum;
  url?: string;
  /** Unique Id to identify this webhook notification. */
  webhookId?: number;
}

export const notificationResponseSchema: Schema<NotificationResponse> = object({
  dateTime: ['dateTime', optional(string())],
  eventName: ['eventName', optional(eventName1EnumSchema)],
  lastResponseCode: ['lastResponseCode', optional(number())],
  lastRetryDateTime: ['lastRetryDateTime', optional(string())],
  retryCount: ['retryCount', optional(number())],
  status: ['status', optional(status1EnumSchema)],
  url: ['url', optional(string())],
  webhookId: ['webhookId', optional(number())],
});
