/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import {
  ToNppCreditPayIdDetails,
  toNppCreditPayIdDetailsSchema,
} from './toNppCreditPayIdDetails';

/** disbursement to NppCreditPayId */
export interface NppCreditPayId {
  disbursementMethod: string;
  /** description for the transaction */
  description?: string;
  toNppCreditPayIdDetails: ToNppCreditPayIdDetails;
  /** This is the amount of funds to be paid */
  amount: number;
  /** Reference will appear on payees statement. Refer to the disbursement object, May be overwritten for some account configurations, contact us for more details. */
  lodgementReference?: string;
}

export const nppCreditPayIdSchema: Schema<NppCreditPayId> = object({
  disbursementMethod: ['disbursementMethod', string()],
  description: ['description', optional(string())],
  toNppCreditPayIdDetails: [
    'toNppCreditPayIdDetails',
    lazy(() => toNppCreditPayIdDetailsSchema),
  ],
  amount: ['amount', number()],
  lodgementReference: ['lodgementReference', optional(string())],
});
