/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import { KeyEnum, keyEnumSchema } from './keyEnum';
import { Value1Enum, value1EnumSchema } from './value1Enum';

export interface Option {
  key?: KeyEnum;
  /** None (No Settlement)<br>  Daily (Every Business Day)<br>  BeginningOfMonth (First Business Day of Month)<br>  EndOfMonth (Last Business Day of Month)<br>  MidMonth (15th of month)<br>  OnDemand (Only when user initiated)<br>  OnDemandWithCatch (User initiated and EOD)<br>  OncePerDay (Will not run at EOD if a manual settlement prior to for same day)<br>  Ignore (Ignore during import)<br> */
  value?: Value1Enum;
}

export const optionSchema: Schema<Option> = object({
  key: ['key', optional(keyEnumSchema)],
  value: ['value', optional(value1EnumSchema)],
});
