/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayIdStatusEnum
 */
export enum PayIdStatusEnum {
  Enable = 'Enable',
  Disable = 'Disable',
  Deregister = 'Deregister',
  Port = 'Port',
}

/**
 * Schema for PayIdStatusEnum
 */
export const payIdStatusEnumSchema: Schema<PayIdStatusEnum> = stringEnum(PayIdStatusEnum);
