/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface PayIdEnquiry {
  /** The payId you enquirying. */
  payId: string;
}

export const payIdEnquirySchema: Schema<PayIdEnquiry> = object({
  payId: ['payId', string()],
});
