/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface PayIdUpdatePayIdName {
  /** The bank account number for the account against when you Register a PayID. */
  bankAccountNumber: number;
  /** Email address for the PayID. */
  payId: string;
  /** Name displayed to the payers in order to identify you. */
  payIdName: string;
}

export const payIdUpdatePayIdNameSchema: Schema<PayIdUpdatePayIdName> = object({
  bankAccountNumber: ['bankAccountNumber', number()],
  payId: ['payId', string()],
  payIdName: ['payIdName', string()],
});
