/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayIdType1Enum
 */
export enum PayIdType1Enum {
  ABN = 'ABN',
  Email = 'Email',
  PhoneNumber = 'PhoneNumber',
  OrganisationId = 'OrganisationId',
  ACN = 'ACN',
}

/**
 * Schema for PayIdType1Enum
 */
export const payIdType1EnumSchema: Schema<PayIdType1Enum> = stringEnum(PayIdType1Enum);
