/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface PayIdRegisterpayId {
  /** The bank account number for the account against which you are trying to Register a PayID */
  bankAccountNumber: number;
  /** Name displayed to the payers in order to identify you. */
  payIdName: string;
  /** Email address for the PayID. */
  payId?: string;
}

export const payIdRegisterpayIdSchema: Schema<PayIdRegisterpayId> = object({
  bankAccountNumber: ['bankAccountNumber', number()],
  payIdName: ['payIdName', string()],
  payId: ['payId', optional(string())],
});
