/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayIdTypeEnum
 */
export enum PayIdTypeEnum {
  ABN = 'ABN',
  Email = 'Email',
  PhoneNumber = 'PhoneNumber',
  OrganisationId = 'OrganisationId',
  ACN = 'ACN',
}

/**
 * Schema for PayIdTypeEnum
 */
export const payIdTypeEnumSchema: Schema<PayIdTypeEnum> = stringEnum(PayIdTypeEnum);
