/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';
import { StatusEnum, statusEnumSchema } from './statusEnum';

export interface PayIdUpdatePayIdStatus {
  /** The bank account number for the account against when you Register a PayID. */
  bankAccountNumber: number;
  /** Email address for the PayID. */
  payId: string;
  /** Status of your PayID. Possible values: Enable, Disable, Deregister, Port */
  status: StatusEnum;
}

export const payIdUpdatePayIdStatusSchema: Schema<PayIdUpdatePayIdStatus> = object(
  {
    bankAccountNumber: ['bankAccountNumber', number()],
    payId: ['payId', string()],
    status: ['status', statusEnumSchema],
  }
);
