/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, number, object, optional, Schema, string } from '../schema';

export interface ReceivablesBatchStatusV1 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  durationMs?: bigint;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors */
  status?: string;
  /** This is a plain English description of the status. */
  statusDescription?: string;
  /** Number of records parsed in the batch file. */
  numberOfRecords?: number;
  /** URL to access the response report. */
  batchUrl?: string;
}

export const receivablesBatchStatusV1Schema: Schema<ReceivablesBatchStatusV1> = object(
  {
    durationMs: ['durationMs', optional(bigint())],
    status: ['status', optional(string())],
    statusDescription: ['statusDescription', optional(string())],
    numberOfRecords: ['NumberOfRecords', optional(number())],
    batchUrl: ['batchUrl', optional(string())],
  }
);
