/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema } from '../schema';
import { SourceAccount1, sourceAccount1Schema } from './sourceAccount1';

export interface ReceivablesUpdateWhiteListingAccount {
  /** Valid receivables bank account number belonging to the Sign-in mAccount. */
  automatcherBankAccountNumber: number;
  /** This is the  sourceAccount */
  sourceAccount?: SourceAccount1;
}

export const receivablesUpdateWhiteListingAccountSchema: Schema<ReceivablesUpdateWhiteListingAccount> = object(
  {
    automatcherBankAccountNumber: ['automatcherBankAccountNumber', number()],
    sourceAccount: [
      'sourceAccount',
      optional(lazy(() => sourceAccount1Schema)),
    ],
  }
);
