/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, number, object, optional, Schema, string } from '../schema';

export interface ReceivablesRefundResponseV1 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  durationMs?: bigint;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors */
  status?: string;
  /** This is a plain English description of the status. */
  statusDescription?: string;
  /** This is a unique reference generated by the calling service. This is a nonce. Its use is to determine if a request has already been received by the Engine. */
  callerUniqueReference?: string;
  /** This is the fee amount excluding GST */
  feeAmountExcludingGst?: number;
  /** This is the GST Component of the fee amount that has been debited from your mAccount */
  feeAmountGstComponent?: number;
  /** This is the total fee amount Including GST that has been debited from your mAccount */
  feeAmountIncludingGst?: number;
  /** This is the Platform ID that is unique to your payment request */
  transactionId?: number;
}

export const receivablesRefundResponseV1Schema: Schema<ReceivablesRefundResponseV1> = object(
  {
    durationMs: ['durationMs', optional(bigint())],
    status: ['status', optional(string())],
    statusDescription: ['statusDescription', optional(string())],
    callerUniqueReference: ['callerUniqueReference', optional(string())],
    feeAmountExcludingGst: ['feeAmountExcludingGst', optional(number())],
    feeAmountGstComponent: ['feeAmountGstComponent', optional(number())],
    feeAmountIncludingGst: ['feeAmountIncludingGst', optional(number())],
    transactionId: ['transactionId', optional(number())],
  }
);
