/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema';

export interface ReceivablesEnquiryPayIdResponseV1 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  durationMs?: bigint;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors */
  status?: string;
  /** This is a plain English description of the status. */
  statusDescription?: string;
  /** The bank account number for the account against which you are trying to Register a PayID */
  bankAccountNumber?: bigint;
  /** Datetime this PayId was last resolved */
  lastResolutionDateTime?: string;
  lastUpdatedDateTime?: string;
  /** Name displayed to the payers in order to identify you */
  payIdName?: string;
  registrationDateTime?: string;
}

export const receivablesEnquiryPayIdResponseV1Schema: Schema<ReceivablesEnquiryPayIdResponseV1> = object(
  {
    durationMs: ['durationMs', optional(bigint())],
    status: ['status', optional(string())],
    statusDescription: ['statusDescription', optional(string())],
    bankAccountNumber: ['BankAccountNumber', optional(bigint())],
    lastResolutionDateTime: ['LastResolutionDateTime', optional(string())],
    lastUpdatedDateTime: ['LastUpdatedDateTime', optional(string())],
    payIdName: ['PayIdName', optional(string())],
    registrationDateTime: ['RegistrationDateTime', optional(string())],
  }
);
