/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface ReceivablesCreate {
  /** The name of the account to be paid into. Not used for validation of incoming payments. */
  bankAccountName: string;
  /** An identifier assigned to the account. Must be unique. If not provided Monoova will generate and return a value automatically. */
  clientUniqueId?: string;
  /** Used to open and close account numbers. Closed account numbers will return all payments made to that account number. If not provided this value defaults to false. The Automatcher account can take up to 5 mins to be registered and become active before a PayID can be assigned or deposits can be made to the account. The status will automatically changes from false to true. */
  isActive?: boolean;
}

export const receivablesCreateSchema: Schema<ReceivablesCreate> = object({
  bankAccountName: ['bankAccountName', string()],
  clientUniqueId: ['clientUniqueId', optional(string())],
  isActive: ['isActive', optional(boolean())],
});
