/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { ResponseEnum, responseEnumSchema } from './responseEnum';
import { ReturnCodeEnum, returnCodeEnumSchema } from './returnCodeEnum';

export interface ReceivablesProcessdirectdebit {
  /** This is the transactionId that was returned when the transaction was executed. */
  transactionId: string;
  /** Accept to accept direct debit transaction. Reject to reject direct debit transaction. */
  response: ResponseEnum;
  /** Text supplied when rejecting a direct debit. */
  rejectionReason?: string;
  /** This is optional field. default is ReferToCustomer. */
  returnCode?: ReturnCodeEnum;
}

export const receivablesProcessdirectdebitSchema: Schema<ReceivablesProcessdirectdebit> = object(
  {
    transactionId: ['transactionId', string()],
    response: ['response', responseEnumSchema],
    rejectionReason: ['rejectionReason', optional(string())],
    returnCode: ['returnCode', optional(returnCodeEnumSchema)],
  }
);
