/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, lazy, object, optional, Schema, string } from '../schema';
import { PayIdDetails, payIdDetailsSchema } from './payIdDetails';

export interface ReceivablesRegisterPayIdResponseV1 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  durationMs?: bigint;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors */
  status?: string;
  /** This is a plain English description of the status. */
  statusDescription?: string;
  payIdDetails?: PayIdDetails;
}

export const receivablesRegisterPayIdResponseV1Schema: Schema<ReceivablesRegisterPayIdResponseV1> = object(
  {
    durationMs: ['durationMs', optional(bigint())],
    status: ['status', optional(string())],
    statusDescription: ['statusDescription', optional(string())],
    payIdDetails: ['PayIdDetails', optional(lazy(() => payIdDetailsSchema))],
  }
);
