/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface ReceivablesRefund {
  /** This is a unique reference generated by the calling service. This is a nonce. Its use is to determine if a request has already been received by the Engine. */
  uniqueReference: string;
  /** This is the transactionId that was returned when the transaction was executed. */
  originalTransactionId: string;
  /** This is the refund amount. */
  refundAmount: number;
  /** It should be brief but contain sufficient information to identify the transactions. E.g. “Refund. Inv#123456”. */
  description?: string;
  /** Payment reference indicating details of the origin of the entry. */
  refundReference?: string;
}

export const receivablesRefundSchema: Schema<ReceivablesRefund> = object({
  uniqueReference: ['uniqueReference', string()],
  originalTransactionId: ['originalTransactionId', string()],
  refundAmount: ['refundAmount', number()],
  description: ['description', optional(string())],
  refundReference: ['refundReference', optional(string())],
});
