/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { SourceAccount4, sourceAccount4Schema } from './sourceAccount4';

export interface ReceivablesGetWhiteListingAccountsResponseV1 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  durationMs?: bigint;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors */
  status?: string;
  /** This is a plain English description of the status. */
  statusDescription?: string;
  /** Valid receivables bank account number belonging to the Sign-in mAccount. */
  automatcherBankAccountNumber?: number;
  /** Object containing source account details */
  sourceAccount?: SourceAccount4[];
}

export const receivablesGetWhiteListingAccountsResponseV1Schema: Schema<ReceivablesGetWhiteListingAccountsResponseV1> = object(
  {
    durationMs: ['durationMs', optional(bigint())],
    status: ['status', optional(string())],
    statusDescription: ['statusDescription', optional(string())],
    automatcherBankAccountNumber: [
      'automatcherBankAccountNumber',
      optional(number()),
    ],
    sourceAccount: [
      'sourceAccount',
      optional(array(lazy(() => sourceAccount4Schema))),
    ],
  }
);
