/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema } from '../schema';
import { SourceAccount, sourceAccountSchema } from './sourceAccount';

export interface ReceivablesCreateWhiteListingAccount {
  /** Valid receivables bank account number belonging to the Sign-in mAccount. */
  automatcherBankAccountNumber: number;
  /** This is the  sourceAccount */
  sourceAccount?: SourceAccount;
}

export const receivablesCreateWhiteListingAccountSchema: Schema<ReceivablesCreateWhiteListingAccount> = object(
  {
    automatcherBankAccountNumber: ['automatcherBankAccountNumber', number()],
    sourceAccount: ['sourceAccount', optional(lazy(() => sourceAccountSchema))],
  }
);
