/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RejectionReasonCodeEnum
 */
export enum RejectionReasonCodeEnum {
  AM02 = 'AM02',
  AM06 = 'AM06',
  AM07 = 'AM07',
  BE05 = 'BE05',
  AG01 = 'AG01',
  MS01 = 'MS01',
  RR02 = 'RR02',
  RR03 = 'RR03',
  BE04 = 'BE04',
}

/**
 * Schema for RejectionReasonCodeEnum
 */
export const rejectionReasonCodeEnumSchema: Schema<RejectionReasonCodeEnum> = stringEnum(RejectionReasonCodeEnum);
