/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ResponseEnum
 */
export enum ResponseEnum {
  Accept = 'Accept',
  Reject = 'Reject',
}

/**
 * Schema for ResponseEnum
 */
export const responseEnumSchema: Schema<ResponseEnum> = stringEnum(ResponseEnum);
