/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ReturnCodeEnum
 */
export enum ReturnCodeEnum {
  ReferToCustomer = 'ReferToCustomer',
  PaymentStopped = 'PaymentStopped',
}

/**
 * Schema for ReturnCodeEnum
 */
export const returnCodeEnumSchema: Schema<ReturnCodeEnum> = stringEnum(ReturnCodeEnum);
