/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';
import { Key6Enum, key6EnumSchema } from './key6Enum';

export interface SendMonthlyStatement {
  key?: Key6Enum;
  value?: boolean;
}

export const sendMonthlyStatementSchema: Schema<SendMonthlyStatement> = object({
  key: ['key', optional(key6EnumSchema)],
  value: ['value', optional(boolean())],
});
