/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import { Key3Enum, key3EnumSchema } from './key3Enum';
import { ValueEnum, valueEnumSchema } from './valueEnum';

export interface SettlementFrequency {
  key?: Key3Enum;
  /** None (No Settlement)<br>  Daily (Every Business Day)<br>  BeginningOfMonth (First Business Day of Month)<br>  EndOfMonth (Last Business Day of Month)<br>  MidMonth (15th of month)<br>  OnDemand (Only when user initiated)<br>  OnDemandWithCatch (User initiated and EOD)<br>  OncePerDay (Will not run at EOD if a manual settlement prior to for same day)<br>  Ignore (Ignore during import)<br> */
  value?: ValueEnum;
}

export const settlementFrequencySchema: Schema<SettlementFrequency> = object({
  key: ['key', optional(key3EnumSchema)],
  value: ['value', optional(valueEnumSchema)],
});
