/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import { AccountStatusEnum, accountStatusEnumSchema } from './accountStatusEnum';

/** This is the  sourceAccount */
export interface SourceAccount {
  /** 6 digits with a '-'. <br/> `at least one of BSB/AccountNumber or AccountName is required` */
  bsbNumber?: string;
  /** 3 to 9 digits. <br/> `at least one of BSB/AccountNumber or AccountName is required` */
  accountNumber?: number;
  /** String of max 140 chars. Not case sensitive. <br/> `at least one of BSB/AccountNumber or AccountName is required` */
  accountName?: string;
  /** enabled/disabled. Default to enabled. */
  accountStatus?: AccountStatusEnum;
}

export const sourceAccountSchema: Schema<SourceAccount> = object({
  bsbNumber: ['bsbNumber', optional(string())],
  accountNumber: ['accountNumber', optional(number())],
  accountName: ['accountName', optional(string())],
  accountStatus: ['accountStatus', optional(accountStatusEnumSchema)],
});
