/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface SourceAccount4 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  accountName?: string;
  /** 3 to 9 digits. */
  accountNumber?: number;
  /** This is a plain English description of the status. enabled/disabled. */
  accountStatus?: string;
  /** 6 digits with a '-'. */
  bsbNumber?: string;
  /** identifier for whiteList sourceAccount */
  id?: number;
}

export const sourceAccount4Schema: Schema<SourceAccount4> = object({
  accountName: ['accountName', optional(string())],
  accountNumber: ['accountNumber', optional(number())],
  accountStatus: ['accountStatus', optional(string())],
  bsbNumber: ['bsbNumber', optional(string())],
  id: ['id', optional(number())],
});
