/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import {
  AccountStatus1Enum,
  accountStatus1EnumSchema,
} from './accountStatus1Enum';

/** This is the  sourceAccount */
export interface SourceAccount1 {
  /** String of max 140 chars. */
  accountName?: string;
  /** 3 to 9 digits. */
  accountNumber?: number;
  /** This is a plain English description of the status. enabled/disabled. */
  accountStatus: AccountStatus1Enum;
  /** 6 digits with a '-'. */
  bsbNumber?: string;
  /** identifier for whiteList sourceAccount */
  id: number;
}

export const sourceAccount1Schema: Schema<SourceAccount1> = object({
  accountName: ['accountName', optional(string())],
  accountNumber: ['accountNumber', optional(number())],
  accountStatus: ['accountStatus', accountStatus1EnumSchema],
  bsbNumber: ['bsbNumber', optional(string())],
  id: ['id', number()],
});
