/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface SubscriptionsListItems {
  /** The type of event to be sent to this URL via callback. Possible values: NPPReceivepayment */
  eventName?: string;
  /** Unique id for the subscription that needs to be updated */
  id?: number;
  /** This is the API endpoint where the call back notification will be sent. */
  targetUrl?: string;
  /** This is the Subscription Status. Can be On/off */
  status?: string;
  /** Last Updated Time */
  lastUpdated?: string;
  /** Created Time */
  createdDate?: string;
}

export const subscriptionsListItemsSchema: Schema<SubscriptionsListItems> = object(
  {
    eventName: ['eventName', optional(string())],
    id: ['id', optional(number())],
    targetUrl: ['targetUrl', optional(string())],
    status: ['status', optional(string())],
    lastUpdated: ['LastUpdated', optional(string())],
    createdDate: ['createdDate', optional(string())],
  }
);
