/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  SubscriptionsListItems,
  subscriptionsListItemsSchema,
} from './subscriptionsListItems';

export interface SubscriptionsListResponseV1 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  durationMs?: bigint;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors */
  status?: string;
  /** This is a plain English description of the status. */
  statusDescription?: string;
  /** List of Subscription Items */
  eventname?: SubscriptionsListItems[];
}

export const subscriptionsListResponseV1Schema: Schema<SubscriptionsListResponseV1> = object(
  {
    durationMs: ['durationMs', optional(bigint())],
    status: ['status', optional(string())],
    statusDescription: ['statusDescription', optional(string())],
    eventname: [
      'eventname',
      optional(array(lazy(() => subscriptionsListItemsSchema))),
    ],
  }
);
