/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, number, object, optional, Schema, string } from '../schema';

export interface SubscriptionsUpdateResponseV1 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  durationMs?: bigint;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors */
  status?: string;
  /** This is a plain English description of the status. */
  statusDescription?: string;
  /** Unique id for the subscription */
  id?: number;
  /** Date time the subscription was last updated */
  dateTime?: string;
  /** The type of event to be sent to this URL via callback. Possible values: NPPReceivepayment */
  eventName?: string;
  /** This is the API endpoint where the call back notification will be sent. */
  targetUrl?: string;
}

export const subscriptionsUpdateResponseV1Schema: Schema<SubscriptionsUpdateResponseV1> = object(
  {
    durationMs: ['durationMs', optional(bigint())],
    status: ['status', optional(string())],
    statusDescription: ['statusDescription', optional(string())],
    id: ['id', optional(number())],
    dateTime: ['dateTime', optional(string())],
    eventName: ['eventName', optional(string())],
    targetUrl: ['targetUrl', optional(string())],
  }
);
