/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { EventNameEnum, eventNameEnumSchema } from './eventNameEnum';

export interface SubscriptionsCreate {
  /** The type of event to be sent to this URL via callback. */
  eventName: EventNameEnum;
  /** This is the API endpoint where the call back notification will be sent. */
  targetUrl: string;
  /** On/Off. Defaults to Off. */
  subscriptionStatus: string;
  /** This token will be sent back with the callback in Authorization header. <br> (Authorization:&nbsp; <strong>[type] [credentials] </strong>&nbsp;(e.x Basic Rjc1234567890jdGMS67890U78...)) <br> When creating the token, both 'type' and 'credentials' are required. */
  securityToken?: string;
}

export const subscriptionsCreateSchema: Schema<SubscriptionsCreate> = object({
  eventName: ['eventName', eventNameEnumSchema],
  targetUrl: ['targetUrl', string()],
  subscriptionStatus: ['subscriptionStatus', string()],
  securityToken: ['securityToken', optional(string())],
});
