/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  NotificationResponse,
  notificationResponseSchema,
} from './notificationResponse';

export interface SubscriptionsReportV1 {
  /** This value represents the total time in milliseconds that the Platform took to process the request. */
  durationMs?: bigint;
  /** This is the status of executing the request.&nbsp;A code of ‘Ok’ indicates no errors */
  status?: string;
  /** This is a plain English description of the status. */
  statusDescription?: string;
  /** Object containing notification details */
  notifications?: NotificationResponse[];
}

export const subscriptionsReportV1Schema: Schema<SubscriptionsReportV1> = object(
  {
    durationMs: ['durationMs', optional(bigint())],
    status: ['status', optional(string())],
    statusDescription: ['statusDescription', optional(string())],
    notifications: [
      'notifications',
      optional(array(lazy(() => notificationResponseSchema))),
    ],
  }
);
