/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, number, object, Schema } from '../schema';

export interface ToBPayDetails {
  /** BPAY Biller code */
  billerCode: number;
  /** BPAY Customer Reference Number. If this field is empty this denotes that the customerReferenceNumber is variable for each bill and should not be reused. */
  referenceNumber: bigint;
}

export const toBPayDetailsSchema: Schema<ToBPayDetails> = object({
  billerCode: ['billerCode', number()],
  referenceNumber: ['referenceNumber', bigint()],
});
