/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ToDirectCreditDetails {
  /** BSB (Bank-State-Branch) number. The format is a string in the following format:&nbsp;‘999-999’. */
  bsbNumber: string;
  /** This is the bank account number. */
  accountNumber: string;
  /** This is the name of the account. Minimum length is 2, Max length is 32. */
  accountName: string;
}

export const toDirectCreditDetailsSchema: Schema<ToDirectCreditDetails> = object(
  {
    bsbNumber: ['bsbNumber', string()],
    accountNumber: ['accountNumber', string()],
    accountName: ['accountName', string()],
  }
);
