/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, number, object, optional, Schema, string } from '../schema';

export interface TokenUpdateBPAY {
  /** The mWallet or mAccount 16-Digit number that owns the payload. */
  accountNumber: string;
  /** The text (GUID) that identifies the token. */
  tokenToUpdate: string;
  /** A simple text description that is associated with the token. For example “Monthly Electricity Bill BPAY”. */
  description?: string;
  /** Biller Code as shown on the Bill. Must be a valid BPAY Biller on token creation. */
  billerCode: number;
  /** Customer Reference Number as shown on the Bill. Must be a valid BPAY Customer Reference Number on token creation */
  customerReferenceNumber: bigint;
  /** Amount as shown on the Bill. Must be a valid amount on token creation. */
  amount: number;
}

export const tokenUpdateBPAYSchema: Schema<TokenUpdateBPAY> = object({
  accountNumber: ['accountNumber', string()],
  tokenToUpdate: ['tokenToUpdate', string()],
  description: ['description', optional(string())],
  billerCode: ['billerCode', number()],
  customerReferenceNumber: ['customerReferenceNumber', bigint()],
  amount: ['amount', number()],
});
