/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface TokenUpdateAustralianBankAccount {
  /** The mWallet or mAccount 16-Digit number that owns the payload. */
  accountNumber: string;
  /** The text (GUID) that identifies the token. */
  tokenToUpdate: string;
  /** A simple text description that is associated with the token. For example “Savings Account”. */
  description?: string;
  /** Name associated with the bank account. */
  bankAccountName: string;
  /** This is the bank account number. */
  bankAccountNumber: number;
  /** Bank-State-Branch number. Format is 3-3 digits. (Eg.'000-000') */
  bsb: string;
}

export const tokenUpdateAustralianBankAccountSchema: Schema<TokenUpdateAustralianBankAccount> = object(
  {
    accountNumber: ['accountNumber', string()],
    tokenToUpdate: ['tokenToUpdate', string()],
    description: ['description', optional(string())],
    bankAccountName: ['bankAccountName', string()],
    bankAccountNumber: ['bankAccountNumber', number()],
    bsb: ['bsb', string()],
  }
);
