/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { PayIdType1Enum, payIdType1EnumSchema } from './payIdType1Enum';

export interface ToNppCreditPayIdDetails {
  /** PayId Identifier of the Payee. */
  payId: string;
  /** PayId Type. Possible values:&nbsp; ABN, Email, PhoneNumber, OrganisationId, ACN */
  payIdType: PayIdType1Enum;
  /** This is the name of the account. */
  accountName: string;
  /** Osko End to End identifier submitted by Payer. */
  endToEndId?: string;
  /** Remitting Entity. <br/> Note&#58; Remitter name must not be able to be mistaken for another entity (e.g. ATO) and we will do checks. */
  remitterName?: string;
}

export const toNppCreditPayIdDetailsSchema: Schema<ToNppCreditPayIdDetails> = object(
  {
    payId: ['payId', string()],
    payIdType: ['payIdType', payIdType1EnumSchema],
    accountName: ['accountName', string()],
    endToEndId: ['endToEndId', optional(string())],
    remitterName: ['remitterName', optional(string())],
  }
);
