/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ToNppCreditBankAccountDetails {
  /** BSB (Bank-State-Branch) number. The format is a string in the following format:&nbsp;‘999-999’. */
  bsbNumber: string;
  /** This is the bank account number. */
  accountNumber: string;
  /** This is the name of the account. */
  accountName: string;
  /** Osko End to End identifier submitted by Payer. */
  endToEndId?: string;
  /** Remitting Entity.<br/> Note&#58; Remitter name must not be able to be mistaken for another entity (e.g. ATO) and we will do checks. */
  remitterName?: string;
}

export const toNppCreditBankAccountDetailsSchema: Schema<ToNppCreditBankAccountDetails> = object(
  {
    bsbNumber: ['bsbNumber', string()],
    accountNumber: ['accountNumber', string()],
    accountName: ['accountName', string()],
    endToEndId: ['endToEndId', optional(string())],
    remitterName: ['remitterName', optional(string())],
  }
);
