/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransactionTypeEnum
 */
export enum TransactionTypeEnum {
  DE = 'DE',
  NPP = 'NPP',
}

/**
 * Schema for TransactionTypeEnum
 */
export const transactionTypeEnumSchema: Schema<TransactionTypeEnum> = stringEnum(TransactionTypeEnum);
