/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, numberEnum } from '../schema';

/**
 * Enum for TransactionCodeEnum
 */
export enum TransactionCodeEnum {
  Enum13 = 13,
  Enum50 = 50,
}

/**
 * Schema for TransactionCodeEnum
 */
export const transactionCodeEnumSchema: Schema<TransactionCodeEnum> = numberEnum(TransactionCodeEnum);
