/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransactionStatusEnum
 */
export enum TransactionStatusEnum {
  Complete = 'Complete',
  Pending = 'Pending',
  Rejected = 'Rejected',
  Dishonoured = 'Dishonoured',
  WaitingOnClearedFunds = 'WaitingOnClearedFunds',
}

/**
 * Schema for TransactionStatusEnum
 */
export const transactionStatusEnumSchema: Schema<TransactionStatusEnum> = stringEnum(TransactionStatusEnum);
