/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, numberEnum } from '../schema';

/**
 * Enum for Value3Enum
 */
export enum Value3Enum {
  Enum70297171 = 70297171,
}

/**
 * Schema for Value3Enum
 */
export const value3EnumSchema: Schema<Value3Enum> = numberEnum(Value3Enum);
