/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, numberEnum } from '../schema';

/**
 * Enum for Value1Enum
 */
export enum Value1Enum {
  EnumNone = 0,
  EnumDaily = 1,
  EnumBeginningOfMonth = 2,
  EnumEndOfMonth = 3,
  EnumMidMonth = 4,
  EnumOnDemand = 5,
  EnumOnDemandWithCatch = 6,
  EnumOncePerDay = 7,
  EnumIgnore = 8,
}

/**
 * Schema for Value1Enum
 */
export const value1EnumSchema: Schema<Value1Enum> = numberEnum(Value1Enum);
