/**
 * Monoova Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ValueEnum
 */
export enum ValueEnum {
  None = 'None',
  Daily = 'Daily',
  BeginningOfMonth = 'BeginningOfMonth',
  EndOfMonth = 'EndOfMonth',
  MidMonth = 'MidMonth',
  OnDemand = 'OnDemand',
  OnDemandWithCatch = 'OnDemandWithCatch',
  OncePerDay = 'OncePerDay',
  Ignore = 'Ignore',
}

/**
 * Schema for ValueEnum
 */
export const valueEnumSchema: Schema<ValueEnum> = stringEnum(ValueEnum);
